/* Project Study Companion — chapter content and quiz data.
   10 chapters, 10 distinct questions each (100 total), retakeable.
   Content summarises the MSc dissertation
   "Steganographic Signing and Filter Traceability in Digital Media".
   Every fact is drawn from the final project report (FPR v1.6). */

const STUDY = [
  /* ================= Chapter 1 ================= */
  {
    id: 1, title: "Introduction", heading: "What problem is being solved? (FPR Chapter 1)",
    sections: [
      { type: "body", text: "Digital images are resized, recompressed, filtered and reposted constantly. Those ordinary steps strip metadata and silently disturb any information hidden inside the pixels." },
      { type: "body", text: "Checking whether an image is \"still the same\" first requires deciding what \"same\" means. Same pixels? Same content? Same origin? Each question needs different evidence, and each is answered by a different signal." },
      { type: "image", src: "assets/fpr_transform_taxonomy.png", caption: "The benchmark maps a fixed set of named image operations (the transform matrix) onto a fixed sample, then measures how each verification signal survives." },
      { type: "body", text: "The project evaluates three distinct signals: a perceptual hash (are two images perceptually related?), a watermark (can a hidden payload be recovered?), and signed provenance (is there a binding claim?). It implements the first two; provenance infrastructure is explicitly out of scope." },
      { type: "body", text: "The central discipline: none of these signals means \"this image is true\". A low hash distance and a recovered watermark are evidence about similarity and signal recovery — never proof of authorship, authenticity or provenance." },
    ],
    questions: [
      { q: "An image is resized and recompressed by a social platform. Which verification signal is MOST likely to be affected first?",
        opts: ["The perceptual hash, because pixel values change", "The signed provenance manifest, because metadata is stripped", "Both equally, because recompression destroys all evidence", "Neither, because platform operations are lossless"], a: 1,
        exp: "Recompression strips metadata first, breaking any manifest binding; hashes and watermarks are then measured against the transformed pixels." },
      { q: "The report separates four constructs: similarity, recovery, integrity and provenance. Why?",
        opts: ["To make the report longer", "Because each construct requires different evidence and is established by a different mechanism", "Because provenance is illegal", "Because hashes cannot be computed"], a: 1,
        exp: "Similarity needs a hash comparison; recovery needs a decoder; integrity needs a byte-exact binding; provenance needs signatures and a trust chain. Conflating them produces over-claiming." },
      { q: "A recovered watermark is best described as:",
        opts: ["Evidence that the embedded payload survived the tested conditions", "Proof the image is authentic", "Proof of who created the image", "A signed provenance claim"], a: 0,
        exp: "Recovery is an observation about signal persistence under named conditions — never an authenticity or authorship verdict." },
      { q: "Which pairing of signal to question is CORRECT?",
        opts: ["Perceptual hash → who created this?", "Watermark → are these two images related?", "Provenance → is there a signed, accountable claim?", "Hash → is the payload intact?"], a: 2,
        exp: "Provenance answers accountability via signed claims. Hashes answer similarity; watermarks answer payload recovery." },
      { q: "Why is the benchmark described as 'robustness screening' rather than a security evaluation?",
        opts: ["It uses too few images", "It tests a controlled set of named, non-adaptive conditions rather than an adaptive attacker", "It only tests JPEG", "It has no dashboard"], a: 1,
        exp: "Screening covers a fixed matrix of benign/careless conditions; adaptive removal, black-box attacks and composed attacks are future work." },
      { q: "A stakeholder asks: 'Does a recovered watermark prove the image is genuine?' The correct answer is:",
        opts: ["Yes, always", "Yes, if bit accuracy is 100%", "No — recovery is signal persistence, not an authenticity verdict", "Only for TrustMark"], a: 2,
        exp: "Recovery establishes that the payload survived; authenticity would require provenance infrastructure that is explicitly out of scope." },
      { q: "Which operation does the report treat as potentially DELIBERATE rather than routine?",
        opts: ["Brightness adjustment", "Crop or rotation", "Platform recompression", "Resizing for a thumbnail"], a: 1,
        exp: "Crops and rotations can be deliberate rearrangement or attacks; brightness, recompression and resizing are routine pipeline steps." },
      { q: "The system boundary of the implemented benchmark explicitly excludes:",
        opts: ["Perceptual hashing and watermark embedding", "Identity, key management, manifests and a trust chain", "Image transforms and validation", "The dashboard interface"], a: 1,
        exp: "Provenance infrastructure (keys, manifests, trust chains) is out of scope; the implemented signals are hashes and watermarks." },
      { q: "Why does the project avoid embedding real user identifiers in payloads?",
        opts: ["Identifiers are too long for the payload", "An identifier payload becomes a tracking mechanism with privacy and misuse risks", "Identifiers break the decoder", "The dataset forbids it"], a: 1,
        exp: "A payload containing an identifier can become a tracking mechanism and expose people to false association; fixed non-personal payloads avoid this." },
      { q: "The strongest defensible claim the project makes about its contribution is:",
        opts: ["A new watermark algorithm", "An auditable, transformation-aware verification framework with explicit evidence limits", "A provenance certificate system", "A complete authenticity service"], a: 1,
        exp: "The contribution is the auditable benchmark and its evidence discipline, not a new algorithm or an authenticity service." },
    ],
  },

  /* ================= Chapter 2 ================= */
  {
    id: 2, title: "Literature Review", heading: "Three signals, three different jobs (FPR Chapter 2)",
    sections: [
      { type: "body", text: "Perceptual hashing maps an image to a short code that stays similar under mild edits; images are compared by Hamming distance (the number of differing bits). Watermarking embeds a hidden payload that a decoder tries to recover after distortion." },
      { type: "body", text: "TrustMark is the learned neural watermark used here. LSB (least-significant-bit) and DCT (discrete cosine transform) are deliberately simple classical baselines. Eight perceptual hash variants — including PDQ — form the non-embedded similarity layer." },
      { type: "image", src: "assets/fig1_hash_robustness.png", caption: "Mean hash bit change (%) across the tested transforms for several hash algorithms." },
      { type: "body", text: "These signals behave differently under the same operation: a watermark can survive a colour change and die in a crop, while a hash stays stable. That is why the report treats them as complementary rather than ranking them as rivals." },
      { type: "body", text: "Provenance completes the picture: C2PA-style manifests bind signed claims to assets, with hard bindings (cryptographic) distinguished from soft bindings (fingerprints and watermarks). This project implements soft-binding signals only." },
    ],
    questions: [
      { q: "Two images' 64-bit perceptual hashes differ in 6 bits. The most defensible conclusion is:",
        opts: ["The images are byte-identical", "The images are likely perceptually related under the tested conditions", "The second image is an attack", "The payload was recovered"], a: 1,
        exp: "A low Hamming distance is evidence of perceptual relatedness — not byte identity, not an attack, and not recovery." },
      { q: "Which statement about TrustMark is correct?",
        opts: ["Its published robustness figures transfer directly to any deployment", "It is a learned encoder/decoder whose local performance must be measured, not assumed", "It replaces the need for provenance", "It only works on PNG"], a: 1,
        exp: "Published claims depend on the model, payload, sample and transforms, so the project measures the local implementation rather than importing numbers." },
      { q: "Why include deliberately weak baselines like LSB alongside TrustMark?",
        opts: ["To make TrustMark look better", "Because a robustness claim must be tied to a specific implementation, payload and transform", "Because LSB is required by C2PA", "To fill the results table"], a: 1,
        exp: "Baselines anchor the comparison: they show that 'robust' is conditional on implementation, not an intrinsic property of the idea." },
      { q: "In C2PA terms, a watermark is an example of a:",
        opts: ["Hard binding", "Soft binding", "Signed claim", "Trust chain"], a: 1,
        exp: "Soft bindings (fingerprints, watermarks) help identify derived content; hard bindings detect byte-exact change. This project implements soft-binding signals only." },
      { q: "Hash distances are normalised by bit length before comparison because:",
        opts: ["PDQ is 256-bit while the others are 64-bit", "It inflates the results", "Images differ in size", "Hashes change over time"], a: 0,
        exp: "Without normalisation, a longer hash would show larger raw distances regardless of behaviour." },
      { q: "A watermark survives brightness change but fails after a centre crop. The most useful inference is:",
        opts: ["The watermark is broken", "Robustness is conditional on the transform family; spatial operations are the weak point", "Brightness is harmless", "Crops are always benign"], a: 1,
        exp: "Behaviour is method- and transform-specific; identifying the weak transform family guides the next experiment." },
      { q: "Which signal would BEST answer 'is this byte-exact copy intact?'",
        opts: ["A perceptual hash", "A watermark", "A cryptographic (hard) binding", "PSNR"], a: 2,
        exp: "Byte-exact integrity is the role of a hard binding; hashes and watermarks are soft signals, and PSNR is a quality metric." },
      { q: "The eight hash variants are described as a 'non-embedded similarity layer' because:",
        opts: ["They are computed from pixels without embedding anything", "They are embedded in metadata", "They require a decoder", "They are encrypted"], a: 0,
        exp: "Hashes derive from content directly; nothing is added to the image, unlike a watermark." },
      { q: "A high hash distance between an original and a shared image means:",
        opts: ["Malicious tampering is proven", "The representations differ substantially — the cause needs other evidence", "The payload survived", "The image is authentic"], a: 1,
        exth: "",
        exp: "Distance measures representational change; attributing it to an attack requires additional evidence." },
      { q: "Why does the project cite both the TrustMark paper and its software repository?",
        opts: ["To increase the reference count", "Because the paper motivates the method and the repository records the exact implementation used", "The paper is paywalled", "Repositories replace citations"], a: 1,
        exp: "The peer-reviewed paper is the scholarly record; the repository pins the version actually measured." },
    ],
  },

  /* ================= Chapter 3 ================= */
  {
    id: 3, title: "Methodology — The Transform Matrix", heading: "Controlling what 'distorted' means (FPR Chapter 3)",
    sections: [
      { type: "body", text: "All methods are tested against the same named operations. The shared module `transforms.py` is the single source of truth, so no method can silently use a different rotation or crop than another." },
      { type: "body", text: "There are 12 categories and 80 named conditions: brightness, contrast, saturation, vibrancy, blur, salt-and-pepper noise, JPEG compression, rotation, scaling, centre crop, random crop, and letterbox padding." },
      { type: "image", src: "assets/fpr_final1200_method_comparison.png", caption: "Per-transform watermark recovery and hash bit-error across the 12 categories at 1,200 images." },
      { type: "body", text: "The values are not a common severity scale. Brightness 0.5, blur radius 2.0, JPEG quality 20 and crop removal 0.5 are only comparable as named conditions within their own family." },
      { type: "body", text: "Operations are applied independently, not as realistic cascades. This makes each condition interpretable, but it means the benchmark screens robustness — it does not model a real publishing pipeline." },
    ],
    questions: [
      { q: "A colleague reports 'my method survives brightness 0.5 better than yours survives JPEG quality 20'. What is the correct response?",
        opts: ["Accept the comparison — both are severity 0.5", "Reject it — parameters are only comparable as named conditions within their own family", "Accept it — brightness and JPEG are equivalent", "Rerun with brightness 20"], a: 1,
        exp: "There is no common severity scale across families; comparisons are valid only within a family at the same named condition." },
      { q: "JPEG compression in the pipeline is implemented by:",
        opts: ["Reducing image dimensions", "Writing a real JPEG at the requested quality and reopening it", "Changing the file extension only", "Adding noise proportional to quality"], a: 1,
        exp: "The transform performs a genuine re-encode so measurements reflect real codec artefacts, not a symbolic label." },
      { q: "Random transforms (random crop, salt-and-pepper noise) derive their seeds from:",
        opts: ["The system clock", "A hash of image ID, transform name and intensity", "A fixed constant", "The image contents"], a: 1,
        exp: "SHA-256-derived seeds make stochastic transforms reproducible across machines and runs." },
      { q: "Letterbox padding is kept as a separate category from centre crop because:",
        opts: ["It is easier to implement", "It changes layout by adding content rather than removing it", "It only affects colour", "It is not a real platform operation"], a: 1,
        exp: "Padding disturbs descriptors differently from content removal, which is exactly why it is measured separately." },
      { q: "The 80 'conditions' are best described as:",
        opts: ["80 images", "80 methods", "The set of named (transform, intensity) pairs", "80 attacks"], a: 2,
        exp: "Each condition is one named transform at one intensity setting." },
      { q: "Why is rotation at 90° implemented differently from other tested angles?",
        opts: ["90° is the only lossless case", "It expands the canvas rather than clipping corners", "It removes colour", "It equals a crop"], a: 1,
        exp: "Non-expanded rotation would clip corners, so the 90° case uses an expanded canvas with a neutral fill." },
      { q: "A reviewer says the benchmark should cascade transforms (e.g. rotate then JPEG). The report's position is:",
        opts: ["Cascades are already included", "Independent application keeps conditions interpretable; composed attacks are recorded as future work", "Cascades are impossible to implement", "Cascades would be unfair"], a: 1,
        exp: "Isolated operations make per-condition interpretation clear; composed pipelines are a documented limitation, not an oversight." },
      { q: "Which transform category would you EXPECT to most damage a DCT-domain watermark?",
        opts: ["Slight brightness increase", "Centre crop removing 80% of the image", "Mild contrast reduction", "Letterbox padding"], a: 1,
        exp: "DCT coefficients depend on block alignment; removing most of the image destroys block structure, while mild photometric changes are survivable." },
      { q: "The phrase 'single source of truth' applied to transforms.py means:",
        opts: ["The file is encrypted", "Every pipeline imports the same definitions, preventing silent configuration drift", "It is the only Python file", "It contains the dataset"], a: 1,
        exp: "Centralising definitions guarantees identical conditions across methods — the foundation of fair comparison." },
      { q: "Vibrancy is implemented as a separate category from saturation because:",
        opts: ["It uses a non-linear HSV adjustment that favours less-saturated pixels", "It is faster", "It only affects red channels", "It is a JPEG setting"], a: 0,
        exp: "The two colour operations are related but not interchangeable, so they remain distinct named conditions." },
    ],
  },

  /* ================= Chapter 4 ================= */
  {
    id: 4, title: "Methodology — The Pipelines", heading: "Four channels, one harness (FPR Chapter 3)",
    sections: [
      { type: "body", text: "The hash pipeline computes a reference hash on the original and a transformed hash for each condition, recording Hamming distance. TrustMark embeds the fixed payload `TM00001`, recording raw bit accuracy (pre-error-correction) and decode presence separately." },
      { type: "body", text: "LSB writes `LSB0001` into the least-significant bit plane and is deliberately fragile. DCT embeds a payload differentially in mid-frequency coefficients and is a stronger classical comparator." },
      { type: "image", src: "assets/fig2_trustmark_robustness.png", caption: "TrustMark detection versus raw bit accuracy by transform — the two measures clearly diverge." },
      { type: "body", text: "Every result row carries image ID, filename, condition, pipeline version and metrics, so any observation can be traced back to an exact source image (checksums in the manifest)." },
      { type: "body", text: "Because methods differ in payload construction and decoder semantics, bit-accuracy rankings are comparative only — they are not claims about capacity or security." },
    ],
    questions: [
      { q: "A TrustMark row shows bit_accuracy = 0.93 and decode_present = false. The correct interpretation is:",
        opts: ["The row is corrupt", "93% of raw bits matched but error correction could not produce a valid message", "The payload decoded perfectly", "The transform was skipped"], a: 1,
        exp: "Raw accuracy and decode presence diverge exactly because ECC has limits — which is why both are recorded." },
      { q: "Why does each result row store the pipeline version?",
        opts: ["For branding", "So results can be traced to the exact code that produced them", "It is required by CSV", "To compress the file"], a: 1,
        exp: "Version fields make the lineage auditable: a result without its producing version cannot be trusted or reproduced." },
      { q: "The LSB baseline writes its 49-bit payload:",
        opts: ["Across all channels equally", "Into the least-significant bits of the first pixels, row-major", "Into DCT coefficients", "Into EXIF metadata"], a: 1,
        exp: "It embeds sequentially into the first N channel values, which is why nearly any pixel change destroys it." },
      { q: "The DCT baseline embeds by:",
        opts: ["Flipping least-significant bits", "Forcing a chosen mid-frequency coefficient pair apart by a strength threshold", "Appending to the file", "Training a network"], a: 1,
        exp: "Differential encoding pushes one coefficient above another by at least the embedding strength, skipping blocks that already satisfy it." },
      { q: "Why is a 'none' (baseline) row recorded for every image?",
        opts: ["To inflate the row count", "To separate encode/decode behaviour from the effect of a transform", "To satisfy the validator", "As a backup"], a: 1,
        exp: "A method may fail with no transform at all; the baseline isolates embedding quality from transform damage." },
      { q: "Two methods score 0.85 and 0.80 mean bit accuracy on the same condition. The report's position on ranking them is:",
        opts: ["The first is definitively better", "The ranking is comparative only — payload structure and decoder semantics differ", "The results must be wrong", "Only recovery can be compared"], a: 1,
        exp: "Different payload lengths, coding and decoder semantics mean scores are engineering observations, not capacity claims." },
      { q: "Which hash variant has a different bit length from the others?",
        opts: ["pHash", "dHash", "PDQ", "aHash"], a: 2,
        exp: "PDQ is 256-bit; the other seven are 64-bit — hence normalisation by bit length." },
      { q: "The hash pipeline computes the reference hash:",
        opts: ["Once per original image", "Once per condition", "Twice per condition", "Never"], a: 0,
        exp: "One reference hash per image is compared against a transformed hash per condition." },
      { q: "A result row cannot be traced to its source image if the manifest lacks:",
        opts: ["Image dimensions", "SHA-256 checksums and image IDs", "The transform list", "The payload"], a: 1,
        exp: "Checksums bind each row to exact source bytes, which is what makes the lineage auditable." },
      { q: "The pipelines share one harness so that:",
        opts: ["The code is shorter", "Every method faces identical conditions and the comparison stays fair", "Results can be merged", "The dashboard can render faster"], a: 1,
        exp: "A shared harness removes configuration drift — the precondition for any fair cross-method statement." },
    ],
  },

  /* ================= Chapter 5 ================= */
  {
    id: 5, title: "Results — The Two-Layer Hybrid", heading: "A second payload channel — our contribution (FPR Sections 4.7/4.11)",
    sections: [
      { type: "body", text: "The project's own contribution is a second, independent payload channel. Alongside TrustMark, a short BCH-coded payload is embedded in the DCT domain with repetition and interleaved placement, decoded by majority vote before error correction." },
      { type: "image", src: "assets/dashboard_fig4_verify_hybrid.png", caption: "The hybrid Sign/Verify interface reporting two-layer recovery: TrustMark TM00001 plus fallback FB01." },
      { type: "body", text: "Two-layer recovery is defined as: the TrustMark payload decodes OR the fallback watermark decodes. A perceptual hash is not a payload channel, so it is deliberately excluded from recovery." },
      { type: "body", text: "Across the 80 transformed conditions the two-layer rate is 67.3%, versus 60.7% for TrustMark alone. The improvement is concentrated on value-level and compression conditions." },
      { type: "body", text: "The honest limit: without geometric registration the fallback cannot rescue rotation, crops or letterbox, because those destroy the spatial layout it relies on." },
    ],
    questions: [
      { q: "An image fails TrustMark decoding but the fallback watermark decodes. Under the project's definition, the variant is:",
        opts: ["Not recovered", "Recovered (two-layer recovery is an OR)", "Recovered only if the hash also passes", "An error case"], a: 1,
        exp: "Recovery is defined as TrustMark decode OR fallback decode; either channel alone satisfies it." },
      { q: "Why is the fallback payload spread across interleaved blocks rather than consecutive ones?",
        opts: ["To improve compression", "So partial crops destroy only a fraction of each bit's repeats, which majority voting tolerates", "To hide it better", "To speed up decoding"], a: 1,
        exp: "Interleaved placement plus majority vote means losing some repeats still leaves enough votes per bit." },
      { q: "The fallback channel would MOST benefit from adding:",
        opts: ["A stronger JPEG encoder", "A geometric registration/synchronisation step", "A larger payload", "A different hash"], a: 1,
        exp: "Its failures are spatial (rotation, crop, letterbox); registration would restore slot alignment — the report's top future work." },
      { q: "Clean (untransformed) two-layer recovery is 99.75%. This primarily demonstrates:",
        opts: ["The benchmark is easy", "Combined embedding does not materially degrade the primary TrustMark channel", "The fallback is perfect", "Hashes are redundant"], a: 1,
        exp: "If layering the fallback broke TrustMark, clean recovery would drop; it does not." },
      { q: "Why is a perceptual hash excluded from the recovery definition?",
        opts: ["Hashes are inaccurate", "A hash carries no payload — it cannot 'recover' a message", "Hashes are proprietary", "Hashes are slower"], a: 1,
        exp: "Recovery means a payload decoded; a hash is only a similarity digest and cannot satisfy that definition." },
      { q: "The fallback uses repetition plus majority voting BEFORE BCH correction because:",
        opts: ["It looks better in charts", "Voting absorbs partial spatial loss first; BCH then corrects residual bit errors", "BCH cannot run alone", "It reduces file size"], a: 1,
        exp: "The two mechanisms address different damage: scattered slot loss (votes) and random bit errors (BCH)." },
      { q: "Overall transformed recovery is 67.3% two-layer vs 60.7% TrustMark. The +6.6pp is concentrated in:",
        opts: ["Rotation and cropping", "Brightness, contrast, saturation, vibrancy and low-quality JPEG", "Letterbox only", "The clean baseline"], a: 1,
        exp: "Dimension-preserving and compression conditions gain most; geometric ones stay near TrustMark-alone levels." },
      { q: "At JPEG quality 5, recovery rises from 2.7% (TrustMark alone) to 69.7% (two-layer). The most defensible reading is:",
        opts: ["The fallback is immune to JPEG", "The fallback channel survives severe recompression where the neural payload does not", "TrustMark failed to embed", "The test was run twice"], a: 1,
        exp: "The DCT-carried fallback tolerates heavy recompression, rescuing variants the neural channel loses." },
      { q: "In the dashboard, selecting the hybrid method and verifying returns:",
        opts: ["Only 'recovered: yes/no'", "Two-layer recovery plus per-channel results for TrustMark and fallback", "Only the fallback payload", "A hash distance"], a: 1,
        exp: "The hybrid result reports the OR outcome and each channel's payload, detection and bit accuracy." },
      { q: "The fallback's design (BCH + repetition + spread) would perform WORST under which condition?",
        opts: ["JPEG quality 35", "90-degree rotation", "Brightness 1.15", "Gaussian blur 1.0"], a: 1,
        exp: "Rotation destroys block alignment entirely; the others leave the slot grid largely intact." },
    ],
  },

  /* ================= Chapter 6 ================= */
  {
    id: 6, title: "Methodology — Metrics & Measurement", heading: "What each number actually means (FPR Section 3.5)",
    sections: [
      { type: "body", text: "Raw bit accuracy is the share of expected message bits recovered before error correction. Payload recovery is whether error correction produced a valid message. These are not the same, and the report never substitutes one for the other." },
      { type: "body", text: "PSNR measures pixel-domain embedding distortion. SSIM measures structural similarity. Both are imperceptibility metrics; neither says anything about recovery." },
      { type: "image", src: "assets/fig3_method_comparison.png", caption: "Mean bit accuracy across the three watermark methods by transform — note how different this picture is from the recovery comparison." },
      { type: "body", text: "The report's sharpest example: the DCT baseline averages 71.98% raw bit accuracy but only 15.26% payload recovery. High bit agreement does not mean a message survived." },
      { type: "body", text: "Decode rates are always reported with their denominator and baseline policy; hash errors are normalised by bit length (PDQ 256-bit, others 64-bit). Keeping these constructs separate is the report's central honesty discipline." },
    ],
    questions: [
      { q: "Method A: 72% bit accuracy, 15% recovery. Method B: 40% bit accuracy, 40% recovery. Which would you deploy to reliably retrieve payloads?",
        opts: ["Method A — higher bit accuracy", "Method B — recovery is what determines whether a message arrives", "Either — they are equivalent", "Neither can be compared"], a: 1,
        exp: "Recovery is the deployment-relevant outcome; Method A's high bit agreement never crosses the ECC threshold." },
      { q: "PSNR increases after re-tuning an embedder. What can you conclude?",
        opts: ["Robustness improved", "The embedding is less visually distorting — nothing about recovery", "Recovery improved", "Security improved"], a: 1,
        exp: "PSNR measures imperceptibility only; robustness and recovery are separate axes." },
      { q: "A decode rate is quoted as '90%'. Before trusting it you should ask:",
        opts: ["Who computed it", "What the denominator was and whether baseline rows were included", "What colour the chart was", "Whether it used Python"], a: 1,
        exp: "A rate without its denominator and baseline policy cannot be interpreted or reproduced." },
      { q: "Hash error fractions are normalised by bit length so that:",
        opts: ["PDQ (256-bit) and 64-bit hashes are comparable", "Results look smaller", "Files compress better", "Charts fit the page"], a: 0,
        exp: "Normalisation prevents the longer PDQ hash from showing artificially larger raw distances." },
      { q: "The worst-algorithm rule (hash ensemble) exists because:",
        opts: ["Averages hide a failing hash behind seven robust ones", "It is faster to compute", "PDQ is always wrong", "Medians are unreliable"], a: 0,
        exp: "Pooling masks a weak hash; taking the weakest algorithm's mean makes the ensemble's failure visible." },
      { q: "'Decode present' should NEVER be described as:",
        opts: ["A decoder event", "A valid message recovery", "A calibrated probability of authenticity", "A binary outcome"], a: 2,
        exp: "Decode is a binary event; calling it a probability of authenticity would be an uncalibrated over-claim." },
      { q: "An encode-only row is excluded from robustness means because:",
        opts: ["It has no transform, so it measures embedding quality rather than transform survival", "It is a duplicate", "It failed validation", "It uses a different payload"], a: 0,
        exp: "Baseline rows isolate embedding behaviour; including them would dilute transform effects." },
      { q: "SSIM is 0.99 after embedding. The correct interpretation is:",
        opts: ["The payload will definitely recover", "The embedding is structurally near-invisible — recovery is a separate question", "The watermark is weak", "The image is authentic"], a: 1,
        exp: "SSIM is an imperceptibility measure; recovery depends on the decoder, not on visual similarity." },
      { q: "Why does the report call metric separation 'a deliberate honesty choice'?",
        opts: ["Because separate metrics look thorough", "Because conflating them lets a weak result appear strong", "Because examiners require it", "Because CSVs need columns"], a: 1,
        exp: "Substituting bit accuracy for recovery (or PSNR for robustness) is precisely how watermarking results get over-claimed." },
      { q: "The threshold 'watermark passes if mean bit accuracy > 0.5' is best described as:",
        opts: ["A security boundary", "A declared analytical convention for screening, not an operating point", "A C2PA requirement", "A calibrated probability"], a: 1,
        exp: "It is an explicit screening convention; calibrated operating points require false-accept/false-rejection analysis." },
    ],
  },

  /* ================= Chapter 7 ================= */
  {
    id: 7, title: "Methodology — Scale & Validation", heading: "Evidence you can trust (FPR Chapters 3–4)",
    sections: [
      { type: "body", text: "The dataset is MS-COCO 2017 validation. Selection is deterministic — the first N JPG files in lexicographic order — with image IDs, dimensions and SHA-256 checksums recorded in a manifest." },
      { type: "body", text: "The completed evidence is at 1,200 images: 768,000 hash rows and 97,200 rows each for TrustMark, LSB, DCT and the fallback channel. A validator rejects wrong coverage or duplicate keys before any analysis." },
      { type: "image", src: "assets/fpr_pilot_final_comparison.png", caption: "Pilot (100-image) versus final (1,200-image) transformed-row means. The scales are reported separately, never pooled." },
      { type: "body", text: "A command using `--image-count 100` cannot validate a 1,200-image run — coverage must be checked at the intended scale. A partial file fails loudly instead of being analysed." },
      { type: "body", text: "Passing the validator establishes completeness and uniqueness. It does not establish scientific validity — that comes from the design, not the script." },
    ],
    questions: [
      { q: "A result file has 97,200 rows but 3,000 duplicate keys. What does the validator conclude?",
        opts: ["The run is complete", "Coverage failed — duplicates inflate counts and hide missing work", "The run is valid but noisy", "Nothing; duplicates are normal"], a: 1,
        exp: "Duplicates mean unique (image, condition) coverage is short of the target — the run is incomplete." },
      { q: "Why must validation run with `--image-count 1200` rather than the default 100?",
        opts: ["100 is faster", "Coverage must be asserted at the intended scale; validating at 100 proves nothing about 1,200", "1200 uses the GPU", "The validator ignores the flag"], a: 1,
        exp: "The expected row count derives from the image count, so the check is only meaningful at the real scale." },
      { q: "SHA-256 checksums in the manifest exist to:",
        opts: ["Compress the images", "Bind each result row to exact source bytes", "Sign the report", "Speed up loading"], a: 1,
        exp: "Checksums make the lineage auditable: a row traces to specific, verified source content." },
      { q: "The historical 100-image pilot and the final1200 results are:",
        opts: ["Pooled into one table", "Separate evidence sets, clearly labelled and never silently combined", "Identical", "Both discarded"], a: 1,
        exp: "Different scales are different evidence; pooling would misrepresent both." },
      { q: "'Passing the validator' is best understood as:",
        opts: ["Proof the hypothesis is true", "A completeness gate that precedes — but does not replace — scientific interpretation", "A peer review", "A security certificate"], a: 1,
        exp: "Coverage checks are a precondition for analysis, not a substitute for validity arguments." },
      { q: "Why is lexicographic (filename-order) selection defensible despite being a convenience sample?",
        opts: ["It selects the best images", "It is deterministic, documented and reproducible — and its non-representativeness is stated", "It is random", "It is required by COCO"], a: 1,
        exp: "The rule removes undocumented choice; the report explicitly does not claim the sample represents all imagery." },
      { q: "The dataset contains images of people. The report's ethical position is that this:",
        opts: ["Is irrelevant because COCO is public", "Requires dataset terms and rights to remain part of the ethical review", "Makes the project illegal", "Only matters commercially"], a: 1,
        exp: "A public dataset is not an ethics-free guarantee; recognisable persons and third-party rights stay on the register." },
      { q: "Which would be the STRONGEST evidence that a results file should not be trusted?",
        opts: ["It is stored as CSV", "Its row count matches but unique image coverage is short", "It was generated on Windows", "It uses commas"], a: 1,
        exp: "Matching totals with short unique coverage is the classic signature of duplicated rows masking missing work." },
      { q: "Reproducibility of the stochastic transforms across machines is achieved by:",
        opts: ["Fixed system seeds", "Seeds derived from image ID + transform + intensity via SHA-256", "Disabling randomness", "Running twice"], a: 1,
        exp: "Deriving seeds from stable identifiers avoids Python's randomised hashing and reproduces conditions exactly." },
      { q: "The report treats 'configured' versus 'completed' differently because:",
        opts: ["Configuration is cheaper", "A configured run (manifest, runner) is not evidence until it completes and validates", "They are synonyms", "Only completed runs use disk"], a: 1,
        exp: "This distinction is the project's core evidence discipline: existence of a runner is not a result." },
    ],
  },

  /* ================= Chapter 8 ================= */
  {
    id: 8, title: "Results — Method Comparison", heading: "What the data actually shows (FPR Chapter 4)",
    sections: [
      { type: "body", text: "The headline comparison spans 96,000 transformed observations and is captured in `FPR_Method_Comparison.xlsx`. Exact payload recovery is the metric that determines whether a message survived." },
      { type: "image", src: "assets/fpr_method_comparison.png", caption: "Watermark baseline comparison across the transforms." },
      { type: "body", text: "Hybrid two-layer: 67.28% recovery. TrustMark alone: 60.73%. DCT baseline: 15.26%. LSB baseline: 4.90%. The hybrid beats TrustMark by about 6.5 percentage points overall." },
      { type: "body", text: "The rescue is not uniform. Low-quality JPEG jumps dramatically (quality 5: 2.7% to 69.7%), while geometric conditions stay near zero without registration." },
      { type: "body", text: "These are descriptive condition-level results, not population estimates and not an authenticity verdict." },
    ],
    questions: [
      { q: "A platform applies JPEG quality 30 to every upload. Which channel would you deploy, and why?",
        opts: ["TrustMark — it is the neural method", "The hybrid — its fallback channel lifts severe-JPEG recovery dramatically", "DCT — highest bit accuracy", "LSB — simplest"], a: 1,
        exp: "At low JPEG quality the fallback rescues recovery (e.g. q20: 42%→93%); TrustMark alone collapses." },
      { q: "The hybrid's +6.6pp overall gain over TrustMark is best characterised as:",
        opts: ["Uniform across all transforms", "Concentrated in value-level and compression conditions, absent in geometric ones", "Present only on clean images", "Statistically significant everywhere"], a: 1,
        exp: "Per-transform data shows the gain in dimension-preserving conditions; rotation/crop remain near baseline." },
      { q: "DCT's profile (72% bit accuracy, 15% recovery) demonstrates that:",
        opts: ["DCT is the best method", "Bit accuracy and recovery measure different things and must not be conflated", "Error correction is unnecessary", "The test was unfair"], a: 1,
        exp: "High raw-bit agreement without crossing the ECC threshold yields almost no recovered messages." },
      { q: "LSB shows 100% recovery on clean images but 4.9% overall. The correct reading is:",
        opts: ["LSB is the most robust method", "The 100% is definitional self-decode of untouched pixels; fragility appears under any transform", "The clean test was wrong", "LSB beats the hybrid"], a: 1,
        exp: "An LSB embed always decodes itself absent modification — the transformed conditions reveal its fragility." },
      { q: "Why are these results described as 'descriptive condition-level aggregates'?",
        opts: ["They are averages over conditions for this fixed sample — not population estimates or per-image guarantees", "They are estimates of all digital imagery", "They are per-image guarantees", "They are calibrated probabilities"], a: 0,
        exp: "A condition mean can hide both failing and passing individual images; no population claim is made." },
      { q: "The comparison workbook's three sheets are:",
        opts: ["Summary, RecoveryByTransform, JPEGQualityLadder", "Hash, Watermark, Ensemble", "Pilot, Final, Delta", "Code, Data, Figures"], a: 0,
        exp: "FPR_Method_Comparison.xlsx contains those three sheets plus two native charts." },
      { q: "Geometric conditions (rotation, crop) show near-zero recovery for ALL channels. The report's response is:",
        opts: ["Claim robustness anyway", "Identify geometric registration/synchronisation as the priority future work", "Remove those transforms", "Blame the dataset"], a: 1,
        exp: "The honest response is to name the missing capability (synchronisation) as the bounded next experiment." },
      { q: "Why is the JPEG quality ladder presented per quality setting rather than as one JPEG average?",
        opts: ["To fill space", "Because degradation is non-monotonic and per-setting behaviour is where decisions are made", "Averages are banned", "It matches the charts"], a: 1,
        exp: "The q10 irregularity (fallback underperforms TrustMark) would be invisible in a single average." },
      { q: "If a stakeholder needs recovery at quality 10, the data says:",
        opts: ["Deploy the hybrid — it handles everything", "No tested channel is reliable there (best ≈32%); this needs a different approach", "Use DCT", "Use LSB"], a: 1,
        exp: "Honesty cuts both ways: the data also shows where none of the channels suffice." },
      { q: "The results support which single-sentence conclusion?",
        opts: ["Watermarking proves authenticity", "Complementary channels with different failure modes outperform any single channel, within tested limits", "Hashes outperform watermarks", "All methods fail everywhere"], a: 1,
        exp: "That is the defensible engineering conclusion — conditional, bounded, and supported by the condition-level data." },
    ],
  },

  /* ================= Chapter 9 ================= */
  {
    id: 9, title: "Artefact — Sign/Verify Dashboard", heading: "The workflow in practice (FPR Section 4.1)",
    sections: [
      { type: "body", text: "The project ships a single-page web app implementing the promised upload → filter → sign → verify workflow, with a dataset banner showing which evidence set is active." },
      { type: "body", text: "You can supply a short custom payload (a name or small copyright string), validated against the chosen method's capacity: TrustMark up to 9 characters, LSB/DCT exactly 7, hybrid fallback up to 4." },
      { type: "image", src: "assets/dashboard_fig3_verify_single.png", caption: "Single-method verification: Detected = Yes, bit accuracy 100%, decoded payload TM00001." },
      { type: "body", text: "The hybrid result reports two-layer recovery plus per-channel detail — e.g. TrustMark TM00001 (100%) and fallback FB01 (98%), recovery Yes." },
      { type: "body", text: "The endpoints embed and recover watermark payloads. They are not cryptographic signing: no keys, manifests, trust chains, or authenticity verdicts. A 'confidence' value is a deterministic function of decode metrics, never an identifier." },
    ],
    questions: [
      { q: "A user wants to embed '© Jane 2026' with the hybrid method. What happens?",
        opts: ["It embeds the full string in both channels", "It is rejected — the fallback channel caps at 4 characters; the user must shorten it", "It silently truncates", "It switches to LSB automatically"], a: 1,
        exp: "The hybrid fallback accepts up to 4 chars; validation rejects longer input with a clear message rather than truncating silently." },
      { q: "The dataset banner showing 'final1200 (validated)' exists to prevent:",
        opts: ["Slow loading", "The classic mistake of inspecting historical pilot data while believing it is the final evidence", "User error in signing", "CSS breakage"], a: 1,
        exp: "The interface states its evidence source explicitly, so historical and final data can never be confused." },
      { q: "After signing with the hybrid and verifying, the result shows TrustMark detected=Yes (100%) and fallback detected=No. The correct reading is:",
        opts: ["Verification failed", "Two-layer recovery = Yes (TrustMark channel alone satisfied the OR)", "The fallback is broken", "Both channels must detect"], a: 1,
        exp: "Recovery is an OR; one channel decoding is sufficient, and per-channel detail shows which." },
      { q: "The verify response's 'confidence' field is best used as:",
        opts: ["A probability the image is authentic", "A transparent, deterministic indicator derived from decode metrics", "A user trust score", "An encryption strength"], a: 1,
        exp: "Confidence is defined in the response itself and derives only from measured decode metrics — never identity or authenticity." },
      { q: "The Sign/Verify endpoints differ from cryptographic signing because they lack:",
        opts: ["Payload validation", "Keys, certificates, manifests and a trust chain", "A web interface", "Error handling"], a: 1,
        exp: "They perform soft-binding embed/recover; cryptographic signing infrastructure is explicitly out of scope." },
      { q: "Why does the dashboard state which CSV directory it is reading?",
        opts: ["Decoration", "Because defaulting to one dataset silently is exactly how historical and final evidence get confused", "For debugging only", "It does not state it"], a: 1,
        exp: "The banner makes the active evidence set explicit — an honesty control, not a feature." },
      { q: "The React frontend exists in the project because:",
        opts: ["React is faster", "The DPP promised a React frontend built from designs, implementing upload → filter → sign → verify", "HTML cannot call APIs", "The supervisor required it"], a: 1,
        exp: "It fulfils the DPP's stated frontend commitment; the API contract is identical to the plain dashboard's." },
      { q: "A user uploads a random image never signed by the system and runs Detect. The honest expected result is:",
        opts: ["All methods report detected=Yes", "Methods generally report not-detected, though ECC decoders can rarely produce false decodes — which is why wrong-payload testing is future work", "The server errors", "Only the hash runs"], a: 1,
        exp: "The system reports per-method results honestly; false-decode behaviour on arbitrary images is a documented limitation." },
      { q: "The dashboard deliberately does NOT include:",
        opts: ["A dataset banner", "An authenticity verdict button", "Method selection", "Preview panes"], a: 1,
        exp: "No authenticity verdict exists anywhere in the system — the interface cannot imply one." },
      { q: "Serving the dashboard against output/results (default) instead of final1200 would:",
        opts: ["Show the same data", "Silently display the historical 100-image evidence — which is why the active dataset is banner-declared and launchers pin the path", "Crash the server", "Speed it up"], a: 1,
        exp: "The default-path hazard is real; the banner plus documented launchers are the controls." },
    ],
  },

  /* ================= Chapter 10 ================= */
  {
    id: 10, title: "Evaluation — Ethics, Limits & Honesty", heading: "What this project does and does not claim (FPR Chapter 5)",
    sections: [
      { type: "body", text: "The project uses a public research dataset and fixed, non-identifier payloads. It recruits no participants and collects no personal data. Dataset terms and third-party rights remain on the ethical register regardless." },
      { type: "body", text: "It deliberately avoids claiming that a recovered watermark proves identity, truth, ownership or provenance. Those require signed manifests, key management and a trust chain — explicitly out of scope." },
      { type: "image", src: "assets/fpr_payload_ecc_dev_sweep.png", caption: "The payload/ECC ablation: tuning the watermark layer is a component-level choice, not a system-level lever." },
      { type: "body", text: "A headline honest finding: the IPR hypothesis of payload recovery above 90% was NOT confirmed. JPEG two-layer recovery is 85.6%, and PNG was never implemented." },
      { type: "body", text: "Every promise is recorded as delivered, partial or not delivered — SSIM, PNG/WebP, stretch, LUT, GIF, and PostgreSQL (since migrated and verified) — rather than reworded into successes." },
    ],
    questions: [
      { q: "The IPR hypothesised >90% payload recovery across JPEG and PNG. The final report states:",
        opts: ["The hypothesis was confirmed", "It was not confirmed — JPEG two-layer reached 85.6% and PNG was never implemented", "It was confirmed after tuning", "It was withdrawn as untestable"], a: 1,
        exp: "Reporting the non-confirmation, with the exact numbers, is the project's central honesty demonstration." },
      { q: "Why can't the project claim a recovered watermark establishes provenance?",
        opts: ["Provenance requires signed manifests, key management and a trust chain — none implemented", "Provenance is illegal", "Watermarks are too weak", "It could, but chooses not to"], a: 0,
        exp: "The claim would require infrastructure that is explicitly out of scope; the report refuses to infer it from recovery." },
      { q: "The ECC ablation's key finding is that system-level robustness is carried by:",
        opts: ["The strongest BCH mode", "The two-layer architecture and hash fallback, not watermark tuning", "The payload length", "The dashboard"], a: 1,
        exp: "All 12 configurations landed within ~0.3pp once the fallback was active — architecture, not tuning, dominates." },
      { q: "Which pair correctly matches promise to final status?",
        opts: ["SSIM → not delivered; React frontend → delivered; PostgreSQL → delivered and verified", "SSIM → delivered; PostgreSQL → not deployed", "React → not delivered; SSIM → partial", "All promises delivered"], a: 0,
        exp: "SSIM was implemented late (10-image sample), the React frontend was built, and PostgreSQL was migrated and count-verified." },
      { q: "The IPR's evidence table once claimed 'database writes confirmed', but no database had been run. The final report handles this by:",
        opts: ["Repeating the claim", "Correcting it — and subsequently actually deploying and verifying the database", "Deleting the database section", "Blaming the IPR"], a: 1,
        exp: "The over-claim is corrected and then made true: the migration was executed with verified counts." },
      { q: "Which limitation does the report state MOST explicitly?",
        opts: ["No false-acceptance, negative-pair or calibration evaluation exists", "The dataset is too large", "There are too many figures", "Python was used"], a: 0,
        exp: "Calibration, negatives, wrong-payload and adaptive attacks are named as required future work, not glossed over." },
      { q: "The dual-use concern acknowledged is that watermark traceability could:",
        opts: ["Never be misused", "Enable surveillance or unjustified content removal if deployed without governance", "Only benefit creators", "Replace copyright law"], a: 1,
        exp: "The same mechanism that supports traceability can become a tracking mechanism — flagged before any deployment claim." },
      { q: "The report's BCS-mapping section is primarily an exercise in:",
        opts: ["Marketing the project", "Aligning conduct (competence, integrity, accurate representation) with concrete project decisions", "Certifying the project", "Listing regulations"], a: 1,
        exp: "Each principle maps to a real decision — e.g. integrity maps to the corrected PDQ and TrustMark metrics." },
      { q: "'A decode event is not a probability' matters because:",
        opts: ["Decodes are slow", "Presenting an uncalibrated binary event as a likelihood would mislead deployers about error rates", "Probabilities are banned", "Decodes are random"], a: 1,
        exp: "Without calibration on negatives and wrong payloads, any probability-like claim would be unfounded." },
      { q: "The single best summary of the project's contribution is:",
        opts: ["A novel watermark algorithm", "An auditable, transformation-aware benchmark whose claims are bounded by explicit evidence", "A provenance service", "A larger dataset"], a: 1,
        exp: "The contribution is the framework plus evidence discipline — with every claim tied to what was actually measured." },
    ],
  },
];
